trigger:
- prod

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      cd backend
      mvn clean compile assembly:single
- task: CopyFiles@2
  inputs:
    contents: backend/target/*.jar
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: ClairvoyantJAR