# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import clairvoyant_pb2 as clairvoyant__pb2


class ClairvoyantServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateDataPoint = channel.unary_unary(
        '/io.clairvoyant.proto.ClairvoyantService/CreateDataPoint',
        request_serializer=clairvoyant__pb2.DataPoint.SerializeToString,
        response_deserializer=clairvoyant__pb2.Ack.FromString,
        )


class ClairvoyantServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateDataPoint(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ClairvoyantServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateDataPoint': grpc.unary_unary_rpc_method_handler(
          servicer.CreateDataPoint,
          request_deserializer=clairvoyant__pb2.DataPoint.FromString,
          response_serializer=clairvoyant__pb2.Ack.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'io.clairvoyant.proto.ClairvoyantService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
