# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clairvoyant.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='clairvoyant.proto',
  package='io.clairvoyant.proto',
  syntax='proto3',
  serialized_options=_b('P\001'),
  serialized_pb=_b('\n\x11\x63lairvoyant.proto\x12\x14io.clairvoyant.proto\"*\n\tDataPoint\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"\x1a\n\x03\x41\x63k\x12\x13\n\x0b\x64\x61taPointId\x18\x01 \x01(\x05\x32\x65\n\x12\x43lairvoyantService\x12O\n\x0f\x43reateDataPoint\x12\x1f.io.clairvoyant.proto.DataPoint\x1a\x19.io.clairvoyant.proto.Ack\"\x00\x42\x02P\x01\x62\x06proto3')
)




_DATAPOINT = _descriptor.Descriptor(
  name='DataPoint',
  full_name='io.clairvoyant.proto.DataPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='io.clairvoyant.proto.DataPoint.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='io.clairvoyant.proto.DataPoint.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=85,
)


_ACK = _descriptor.Descriptor(
  name='Ack',
  full_name='io.clairvoyant.proto.Ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataPointId', full_name='io.clairvoyant.proto.Ack.dataPointId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['DataPoint'] = _DATAPOINT
DESCRIPTOR.message_types_by_name['Ack'] = _ACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataPoint = _reflection.GeneratedProtocolMessageType('DataPoint', (_message.Message,), dict(
  DESCRIPTOR = _DATAPOINT,
  __module__ = 'clairvoyant_pb2'
  # @@protoc_insertion_point(class_scope:io.clairvoyant.proto.DataPoint)
  ))
_sym_db.RegisterMessage(DataPoint)

Ack = _reflection.GeneratedProtocolMessageType('Ack', (_message.Message,), dict(
  DESCRIPTOR = _ACK,
  __module__ = 'clairvoyant_pb2'
  # @@protoc_insertion_point(class_scope:io.clairvoyant.proto.Ack)
  ))
_sym_db.RegisterMessage(Ack)


DESCRIPTOR._options = None

_CLAIRVOYANTSERVICE = _descriptor.ServiceDescriptor(
  name='ClairvoyantService',
  full_name='io.clairvoyant.proto.ClairvoyantService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=115,
  serialized_end=216,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateDataPoint',
    full_name='io.clairvoyant.proto.ClairvoyantService.CreateDataPoint',
    index=0,
    containing_service=None,
    input_type=_DATAPOINT,
    output_type=_ACK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLAIRVOYANTSERVICE)

DESCRIPTOR.services_by_name['ClairvoyantService'] = _CLAIRVOYANTSERVICE

# @@protoc_insertion_point(module_scope)
